# Generated by Django 4.2.3 on 2023-07-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('pet_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=13)),
                ('problem', models.TextField(blank=True)),
            ],
        ),
    ]
